# Generated by Django 5.2.1 on 2025-05-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creds', '0002_user_first_name_user_last_name_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='email verified'),
        ),
    ]
